name: lyncs
channels:
  - defaults
dependencies:
  - python=3.10.8
  - numpy
  - matplotlib  # for plots
  - scipy       # for making random U(N) (hence SU(N) matrices
  - typing      # type hints
  - pip
  - mypy        # type checking
  - jupyter     # for notebooks
  - flake8      # for style checking
  - pip:
    - gvar      # for doing statistics
    - lyncs_io  # for io
